---
abstract: 'find, build and install the mmseqs2 tools'
author:
  - 'Christos Argyropoulos <chrisarg@gmail.com>'
build_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  Alien::Build: '2.70'
  Alien::Build::MM: '0.32'
  Alien::Build::Plugin::Build::CMake: '0.99'
  Alien::Build::Plugin::Download::GitHub: '0'
  ExtUtils::MakeMaker: '6.52'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-SeqAlignment-MMseqs2
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Alien::SeqAlignment::MMseqs2:
    file: lib/Alien/SeqAlignment/MMseqs2.pm
    version: '0.01'
requires:
  Alien::Base: '0.038'
  Carp: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  IRC: irc://irc.perl.org/#native
  homepage: https://github.com/chrisarg/alien-seqalignment-mmseqs2
  repository: https://github.com/chrisarg/alien-seqalignment-mmseqs2.git
version: '0.01'
x_alienfile:
  generated_by: 'Dist::Zilla::Plugin::AlienBuild version 0.32'
  requires:
    share:
      Alien::Build::Plugin::Download::Negotiate: '1.30'
      Alien::cmake3: '0.02'
      Archive::Tar: '0'
      Config: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      IO::Zlib: '0'
      Mojo::DOM58: '1.00'
      Mozilla::CA: '0'
      Net::SSLeay: '1.49'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
